<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>comment_txtArea</name>
   <tag></tag>
   <elementGuidId>51abe3b3-3dea-4df1-bc81-65ecaa330c2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#addCandidate_comment</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=addCandidate_comment&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#addCandidate_comment</value>
      <webElementGuid>59e34c28-2790-491d-9dfd-2373d2d6ca1d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
